include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - avoid_print
    - avoid_function_literals_in_foreach_calls
    - prefer_const_constructors
    - prefer_const_declarations
    - use_super_parameters

analyzer:
  exclude:
    - build/**
    - lib/firebase_options.dart
